language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustc -V
  - cargo -V
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH
  - export CARGO_TARGET_DIR="$TRAVIS_BUILD_DIR/target"

script:
  - travis-cargo build -- -j1
  - travis-cargo test
  - travis-cargo test -- --manifest-path assimp-sys-test/Cargo.toml
  - travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
