[package]
name = "test_rust"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]

[dependencies]
typed-arena = "1.3.0"
glutin = "0.8.1"
gl = "*"
bitflags = "0.9"
lazy_static = "0.2.8"
smallvec = "0.4.1"
libc = "*"
