[package]
name = "autograph-derive"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]

[dependencies]
autograph = { path = "../autograph" }
bitflags = "0.9"
lazy_static = "0.2.8"
log = "*"
regex = "0.2.2"
syn = "*"
quote = "*"

[lib]
proc-macro = true
