[package]
name = "autograph-derive"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]

[dependencies]
lazy_static = "0.2.8"
log = "*"
quote = "*"
syn = "*"
proc-macro2 = "*"
memoffset="*"

[dependencies.darling]
path = "../ext/darling"

[lib]
proc-macro = true
