[package]
name = "autograph-derive"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]

[dependencies]
autograph = { path = "../autograph" }
lazy_static = "0.2.8"
log = "*"
quote = "0.4"
syn = "0.12"
darling = "*"
proc-macro2 = "*"

[lib]
proc-macro = true
