[package]
name = "autograph-derive"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]

[dependencies]
lazy_static = "0.2.8"
log = "*"
quote = "*"
syn = "*"
darling = "*"
proc-macro2 = "*"

[lib]
proc-macro = true
